set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE TRYBE;
    SELECT 'CREATE DATABASE TRYBE'
    WHERE NOT EXISTS (SELECT FROM pg_database where datname = 'TRYBE')
EOSQL

